### ISSUE TITLE
setting of bounding box

### ISSUE THREAD

**Issue by NguyenTriTrinh** [pablopalafox/npms#2]
Appreciate your interesting work. I am a little confused about the setting of the bounding box in your experiments. You set  `compute_bbox = False `as default in normalize_dataset.py,  it means you use a predefined bounding box(bbox.json) to normalize the meshes. If I set `compute_bbox = True ` to compute them in the cape datasets, I should get the same results as bbox.json, right?  and the boundary should be set as [-0.5, 0.5] in both two options.

**Comment by pablopalafox** [comment]
Hi @NguyenTriTrinh, sorry for the super late response. The high-level goal is to get identities coming from different datasets in roughly the same scale and position. So I played a bit with some pre-saved bbox.json and so on, and might have forgotten to properly document it. But yeah, overall, if dealing with different datasets, try to get them in roughly the same scale and roughly aligned. If dealing with only one dataset, this is not that important, since the identities in their tposes will most likely be aligned already (like in CAPE).
